version: '3.8'

services:
  db:
    image: postgres:15
    container_name: company_dashboard_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: company_dashboard
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 